version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: todo-sql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TodoDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False
    ports:
      - "5000:5000"

volumes:
  mssqldata: