version: '3.9'

services:
 db:
   image: mcr.microsoft.com/mssql/server:2019-latest
   environment:
     SA_PASSWORD: "Your_password123"
     ACCEPT_EULA: "Y"
     MSSQL_MEMORY_LIMIT_MB: "1024"
   ports:
     - "1433:1433"
   volumes:
     - mssqldata:/var/opt/mssql

 api:
   image: itegrisu/todo:latest
   depends_on:
     - db
   environment:
     ConnectionStrings__DefaultConnection: "Server=db;Database=TodoDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False"
     ASPNETCORE_URLS: "http://+:5000"
   ports:
     - "5000:5000"

volumes:
 mssqldata: